export const DEPARTMENTS_LIST_REQUEST = "DEPARTMENTS_LIST_REQUEST";
export const DEPARTMENTS_LIST_SUCCESS = "DEPARTMENTS_LIST_SUCCESS";
export const DEPARTMENTS_LIST_FAIL = "DEPARTMENTS_LIST_FAIL";

export const DEPARTMENTS_CREATE_REQUEST = "DEPARTMENTS_CREATE_REQUEST";
export const DEPARTMENTS_CREATE_SUCCESS = "DEPARTMENTS_CREATE_SUCCESS";
export const DEPARTMENTS_CREATE_FAIL = "DEPARTMENTS_CREATE_FAIL";
